import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navigation from "../components/Navigation"
import AppProvider from "./context/AppProvider"
import Link from "next/link"
const inter = Inter({ subsets: ["latin"] })

import {
	Bell,
	CircleUser,
	Home,
	LineChart,
	Menu,
	NotebookTabs,
	Package,
	Package2,
	Search,
	ShoppingCart,
	TableCellsSplit,
	Users,
	Utensils,
	UtensilsCrossed,
} from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/components/ui/card"
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { Input } from "@/components/ui/input"
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet"
import { usePathname } from "next/navigation"
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} flex`}>
				<AppProvider>
					<div className='min-h-screen w-full '>
						<div className='flex flex-col'>
							<header className='flex h-14 items-center justify-between gap-4 bg-white border-b fixed top-0 left-0 right-0 z-10 px-4 lg:h-[60px] lg:px-6 '>
								<Link
									href='/'
									className='flex items-center gap-2 font-semibold'>
									<UtensilsCrossed className='h-6 w-6' />
									<span className=''>Bookly</span>
								</Link>
								<Link href={"/administration"}>
									<Button variant={"outline"}>Admin Login</Button>
								</Link>
							</header>
							<main className='container flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6 mt-16'>
								{children}
							</main>
						</div>
					</div>
				</AppProvider>
			</body>
		</html>
	)
}
