import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navigation from "../components/Navigation"
import AppProvider from "./context/AppProvider"
import Link from "next/link"
const inter = Inter({ subsets: ["latin"] })

import {
	Bell,
	CircleUser,
	Home,
	LineChart,
	Menu,
	NotebookTabs,
	Package,
	Package2,
	Search,
	ShoppingCart,
	TableCellsSplit,
	Users,
	Utensils,
	UtensilsCrossed,
} from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/components/ui/card"
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { Input } from "@/components/ui/input"
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet"
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} flex`}>
				<AppProvider>
					<div className='grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]'>
						<div className='hidden border-r bg-muted/40 md:block'>
							<div className='flex h-full max-h-screen flex-col gap-2'>
								<div className='flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6'>
									<Link
										href='/'
										className='flex items-center gap-2 font-semibold'>
										<UtensilsCrossed className='h-6 w-6' />
										<span className=''>Bookly</span>
									</Link>
									<Button
										variant='outline'
										size='icon'
										className='ml-auto h-8 w-8'>
										<Bell className='h-4 w-4' />
										<span className='sr-only'>Toggle notifications</span>
									</Button>
								</div>
								<div className='flex-1'>
									<nav className='grid items-start px-2 text-sm font-medium lg:px-4'>
										<Link
											href='/restaurants'
											className='flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary'>
											<Utensils className='h-4 w-4' />
											Restaurants
										</Link>
										<Link
											href='/bookings'
											className='flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary'>
											<NotebookTabs className='h-4 w-4' />
											Buchungen
											<Badge className='ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full'>
												6
											</Badge>
										</Link>

										<Link
											href='/administration'
											className='flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary'>
											<TableCellsSplit className='h-4 w-4' />
											Administration
										</Link>
									</nav>
								</div>
							</div>
						</div>
						<div className='flex flex-col'>
							<header className='flex h-14 items-center gap-4 border-b bg-muted/40 px-4 lg:h-[60px] lg:px-6'>
								<Sheet>
									<SheetTrigger asChild>
										<Button
											variant='outline'
											size='icon'
											className='shrink-0 md:hidden'>
											<Menu className='h-5 w-5' />
											<span className='sr-only'>Toggle navigation menu</span>
										</Button>
									</SheetTrigger>
									<SheetContent side='left' className='flex flex-col'>
										<nav className='grid gap-2 text-lg font-medium'>
											<Link
												href='#'
												className='flex items-center gap-2 text-lg font-semibold'>
												<Package2 className='h-6 w-6' />
												<span className='sr-only'>Bookly</span>
											</Link>
											<Link
												href='/restaurants'
												className='mx-[-0.65rem] flex items-center gap-4 rounded-xl px-3 py-2 text-muted-foreground hover:text-foreground'>
												<Utensils className='h-5 w-5' />
												Restaurants
											</Link>
											<Link
												href='/bookings'
												className='mx-[-0.65rem] flex items-center gap-4 rounded-xl bg-muted px-3 py-2 text-foreground hover:text-foreground'>
												<NotebookTabs className='h-5 w-5' />
												Buchungen
												<Badge className='ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full'>
													6
												</Badge>
											</Link>
											<Link
												href='/administration'
												className='mx-[-0.65rem] flex items-center gap-4 rounded-xl px-3 py-2 text-muted-foreground hover:text-foreground'>
												<TableCellsSplit className='h-5 w-5' />
												Administration
											</Link>
										</nav>
									</SheetContent>
								</Sheet>
								<div className='w-full flex-1'>
									<form>
										<div className='relative'>
											<Search className='absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground' />
											<Input
												type='search'
												placeholder='Restaurant suchen'
												className='w-full appearance-none bg-background pl-8 shadow-none md:w-2/3 lg:w-1/3'
											/>
										</div>
									</form>
								</div>
								<DropdownMenu>
									<DropdownMenuTrigger asChild>
										<Button
											variant='secondary'
											size='icon'
											className='rounded-full'>
											<CircleUser className='h-5 w-5' />
											<span className='sr-only'>Toggle user menu</span>
										</Button>
									</DropdownMenuTrigger>
									<DropdownMenuContent align='end'>
										<DropdownMenuLabel>Mein Account</DropdownMenuLabel>
										<DropdownMenuSeparator />
										<DropdownMenuItem>Einstellungen</DropdownMenuItem>
										<DropdownMenuItem>Support</DropdownMenuItem>
										<DropdownMenuSeparator />
										<DropdownMenuItem>Ausloggen</DropdownMenuItem>
									</DropdownMenuContent>
								</DropdownMenu>
							</header>
							<main className='flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6'>
								{children}
							</main>
						</div>
					</div>
				</AppProvider>
			</body>
		</html>
	)
}
